name: Mirror to vercel-pages

on:
  push:
    branches:
      # 여기서 'main'을 lunchcharm 레포의 기본 브랜치 이름으로 변경하세요.
      - main 

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up SSH key
        run: |
          echo "${{ secrets.DEPLOY_KEY_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Mirror to vercel-pages
        run: |
          git remote add mirror git@github.com:choirock/vercel-pages.git
          git push mirror main --force
